---
- name: Hello Events
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Print event with linux
      condition: event.target_os == "linux"
      action:
        debug: