---
- name: panos test
  hosts: all

  sources:
    - name: Listen logs via HTTP server Profile
      paloaltonetworks.panos.logs:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Debug event
      condition: event.payload is defined
      actions:
        - debug: 
            msg: "{{ event }}"
        - print_event: