---
- name: panos test
  hosts: all

  sources:
    - name: Listen logs via HTTP server Profile
      paloaltonetworks.panos.logs:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Say Hello
      condition: event.payload.opaque is match("Commit job succeeded")
      # condition: event.payload.opaque == "ab"
      action:
        run_job_template:
          name: Demo Job Template    # 実行したいジョブテンプレート名
          organization: Default