---
- name: Hello Events
  hosts: all

  sources:
    - paloaltonetworks.panos.logs:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Debug event
      condition: event is defined
      action:
        debug:
          msg: "{{ event }}"