---
- name: Run Workflow
  hosts: all

  sources:
    - ansible.eda.range:
        limit: 5

  rules:
    - name: Run Workflow
      condition: event.payload is defined
      action:
        run_job_template:
          name: Demo Job Template
          organization: Default

