---
- name: Hello Events
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001

  rules:
    - name: Say Hello
      condition: 1 == 1
      action:
        debug:
          msg: "{{ event }}"
