---
- name: Hello Events
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Say Hello
      condition: 1 == 1
      action:
        debug:
          msg: e

    # - name: print output
    #   condition: event is defined
    #   action:
    #     print_event:
    #       pretty: true
    #       var_root: evnet