---
- name: Run Workflow
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Run Workflow
      condition: event.payload.message == "sakana"
      action:
        run_workflow_template:
          name: wf01
          organization: Default

